CREATE DATABASE IF NOT EXISTS nyccrashes;

USE nyccrashes;

CREATE TABLE IF NOT EXISTS crash (
    CRASH_DATE CHAR(10),
    CRASH_TIME CHAR(5),
    BOROUGH VARCHAR(13),
    ZIP_CODE CHAR(5),
    LATITUDE DOUBLE,
    LONGITUDE DOUBLE,
    LOCATION CHAR(25),
    ON_STREET_NAME VARCHAR(32),
    CROSS_STREET_NAME VARCHAR(32),
    OFF_STREET_NAME VARCHAR(40),
    NUMBER_OF_PERSONS_INJURED TINYINT UNSIGNED,
    NUMBER_OF_PERSONS_KILLED TINYINT UNSIGNED,
    NUMBER_OF_PEDESTRIANS_INJURED TINYINT UNSIGNED,
    NUMBER_OF_PEDESTRIANS_KILLED TINYINT UNSIGNED,
    NUMBER_OF_CYCLIST_INJURED TINYINT UNSIGNED,
    NUMBER_OF_CYCLIST_KILLED TINYINT UNSIGNED,
    NUMBER_OF_MOTORIST_INJURED TINYINT UNSIGNED,
    NUMBER_OF_MOTORIST_KILLED TINYINT UNSIGNED,
    CONTRIBUTING_FACTOR_VEHICLE_1 VARCHAR(53),
    CONTRIBUTING_FACTOR_VEHICLE_2 VARCHAR(53),
    CONTRIBUTING_FACTOR_VEHICLE_3 VARCHAR(53),
    CONTRIBUTING_FACTOR_VEHICLE_4 VARCHAR(43),
    CONTRIBUTING_FACTOR_VEHICLE_5 VARCHAR(43),
    COLLISION_ID INT PRIMARY KEY,
    VEHICLE_TYPE_CODE_1 VARCHAR(38),
    VEHICLE_TYPE_CODE_2 VARCHAR(38),
    VEHICLE_TYPE_CODE_3 VARCHAR(35),
    VEHICLE_TYPE_CODE_4 VARCHAR(35),
    VEHICLE_TYPE_CODE_5 VARCHAR(35)
);